site_name: Amba Analysis Worker Perculator
site_description: 'documentation for amba-analysis-worker-perculator'
site_author: 'Lukas Jesche'
docs_dir: docs/
repo_name: 'ambalytics/amba-analysis-worker-perculator'
repo_url: 'https://github.com/ambalytics/amba-analysis-worker-perculator'
nav:
    - Home: index.md
    - Code Reference:
        twitter supervisor: twitter_supervisor_ref.md
        twitter perculator: twitter_perculator_ref.md
        doi resolver: doi_resolver_ref.md

theme:
  name: material
  palette:
    scheme: preference
    primary: teal
    accent: purple

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("src")