site_name: Amba Analysis Worker Percolator
site_description: 'documentation for amba-analysis-worker-percolator'
site_author: 'Lukas Jesche'
docs_dir: docs/
repo_name: 'ambalytics/amba-analysis-worker-percolator'
repo_url: 'https://github.com/ambalytics/amba-analysis-worker-percolator'
nav:
    - Home: index.md
    - Code Reference:
        twitter percolator: twitter_percolator_ref.md
        doi resolver: doi_resolver_ref.md

theme:
  name: material
  palette:
    scheme: preference
    primary: teal
    accent: purple

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("src")