name: Testing

on:
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  package:
    name: Testing
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade sentry-sdk
          pip install --upgrade coverage
          pip install -r src/requirements.txt
      - name: Run Tests
        run: |
          coverage run -m unittest discover
          coverage report